version: '3.8'

services:
  memadmin:
    image: hatamiarash7/memcached-admin:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
     - '${APP_PORT}:80'
    environment: 
     - 'MEMCACHED_HOST=$APP_HOST'

networks:
  default:
      name: ${APP_NETWORK}